In [1]:
import csv
from csv import reader
from sys import argv
#from sklearn import linear_model
import numpy as np

dataset = []
labelset = []
with open('/Users/ywkim/Desktop/ML/COMP540/Kaggle_SVHN/train.csv', 'r') as file:
    csv_reader = reader(file)
    next(csv_reader, None) #skip header
    for row in csv_reader:
        if not row:
            continue
        label = int(row[0])
        data = row[1:]
        data = map(lambda x: float(x), data)
        dataset.append(data)
        labelset.append(label)
X = np.array(dataset)
X_train = X.reshape(32, 32, 3, -1).transpose(3,0,1,2)
Y_train = np.array(labelset)

In [2]:
print X.shape

(73257, 3072)


In [36]:

def weightedAverage(pixel):
    return 0.299*pixel[0] + 0.589*pixel[1] + 0.114*pixel[2]  

image = X_train[3]
gray = np.zeros((image.shape[0], image.shape[1]))
for rownum in range(len(image)):
    for colnum in range(len(image[rownum])):
        gray[rownum][colnum] = weightedAverage(image[rownum][colnum])

print X_train[3]
print gray
for i in range(32):
    X_train[3][i][i] = np.array([gray]*3).reshape(32,32,3)
print X_train[3][0][0]

[[[  18.   65.  147.]
  [  15.   69.  159.]
  [  11.   70.  162.]
  ..., 
  [  60.  145.  235.]
  [  57.  143.  230.]
  [  59.  143.  233.]]

 [[  15.   65.  152.]
  [  21.   80.  174.]
  [  23.   88.  188.]
  ..., 
  [  57.  145.  235.]
  [  54.  142.  231.]
  [  58.  143.  234.]]

 [[  34.   86.  169.]
  [  36.  100.  190.]
  [  37.  110.  205.]
  ..., 
  [  53.  142.  232.]
  [  53.  141.  231.]
  [  55.  143.  233.]]

 ..., 
 [[ 235.  254.  255.]
  [ 195.  228.  255.]
  [ 131.  177.  226.]
  ..., 
  [  53.  136.  228.]
  [  54.  138.  228.]
  [  53.  135.  221.]]

 [[ 218.  244.  255.]
  [ 179.  218.  255.]
  [ 120.  172.  229.]
  ..., 
  [  54.  137.  229.]
  [  54.  138.  228.]
  [  52.  134.  218.]]

 [[ 142.  182.  234.]
  [ 119.  171.  231.]
  [  97.  162.  230.]
  ..., 
  [  61.  140.  233.]
  [  61.  142.  231.]
  [  62.  143.  225.]]]
[[  60.425   63.252   62.987 ...,  130.135  127.49   128.43 ]
 [  60.098   73.235   80.141 ...,  129.238  126.118  128.245]
 [  80.086   91.3